---
- name: Check Red Hat and Java versions
  hosts: dev
  remote_user: sycat
  become: false
  gather_facts: true

  tasks:
    - name: Display Red Hat version
      debug:
        msg:
          - "Hostname: {{ inventory_hostname }}"
          - "OS: {{ ansible_distribution }}"
          - "Version: {{ ansible_distribution_version }}"
          - "Major Version: {{ ansible_distribution_major_version }}"
          - "Kernel: {{ ansible_kernel }}"

    - name: Check Java version
      command: java -version
      register: java_version
      changed_when: false
      failed_when: false

    - name: Display Java version
      debug:
        msg: >-
          {{
            java_version.stderr_lines
            if java_version.rc == 0
            else ['Java is not installed or not in the PATH']
          }}
