
---
  - name: install java 8
    yum: name=java-1.8.0-openjdk.x86_64 state=latest 

  - name: Create tomcat group
    group: name=tomcat state=present

  - name: set SELinux to permissive
    shell: 'setenforce 0'

  - name: Create tomcat user
    user: name=tomcat group=wheel state=present

  - name: Create tomcat directory in root
    file: path=/tomcat owner=tomcat group=tomcat state=directory mode=0777

  - name: download tomcat
    get_url: 
      url: "{{ tomcat8_source }}" 
      dest: /tomcat

  - name: Extract apache-tomcat-8.0.32.tar.gz
    unarchive:
      src: "/tomcat/{{ tomcat8_pkg }}"
      dest: /tomcat/
      remote_src: yes

  - name: download jenkins
    get_url: url={{ jenkins_pkg }} dest=/tomcat/apache-tomcat-8.0.32/webapps

  - name: copy tomcat-users.xml to tomcat_home/conf
    copy: src=roles/tomcat/files/tomcat-users.xml dest=/tomcat/apache-tomcat-8.0.32/conf owner=tomcat group=tomcat mode=0755

  - name: delete tomcat-8.0 directory if present
    file: path=/tomcat/tomcat-8.0 state=absent

  - name: rename apache-tomcat to tomcat-8.0
    command: mv /tomcat/apache-tomcat-8.0.32 /tomcat/tomcat-8.0

  - name: change apache-tomcat-8 ownership to tomcat-8
    file: path=/tomcat owner=tomcat group=tomcat mode=0755 recurse=yes

  - name: copy tomcat.service to systemd
    copy: src=roles/tomcat/files/tomcat.service dest=/etc/systemd/system owner=root group=root mode=0755

  - name: start tomcat service
    systemd:
      name: tomcat
      state: started
      enabled: yes
      daemon_reload: yes
